import React from 'react'
import Head from 'next/head'
import Link from 'next/link'

export default function Layout({children, title}) {
  return (
      <div>
           <Head>
              <title>{title ? title + '-DutchStore' : 'Super Estore'}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
          </Head>
          
          <div className='flex min-h-screen flex-col justify-between'>
              <header>
                  <nav className="flex h-12 items-center px-4 justify-between shadow-md">
                      <Link href="/">
                          <p className="text-lg font-bold">DutchStore</p>
                      </Link>

                      <div className="flex">
                          <Link href="/cart"><p className="p-2">Cart</p></Link>
                          <Link href="/login"><p className="p-2">Login</p></Link>
                      </div>
                  </nav>
              </header>
         
          <main className="container m-auto mt-4 px-4">{children}</main>
          <footer className="flex h-10 justify-center items-center shadow-inner">Copyright @ 2023 DutchStore</footer> 
          </div>
      </div>
  )
}